version: '3'

services:
  jupyter:
    build: .
    image: yelp-project
    container_name: yelp
    volumes:
      - ./datasets:/app/datasets
    env_file:
      - ./.env_file
    ports:
      - "8888:8888"