version: '3'

services:
  jupyter:
    build: .
    image: yelp-project
    container_name: yelp
    volumes:
      - ./data:/app/data
    env_file:
      - ./.env_file
    ports:
      - "8888:8888"
    command:
      - /start